# Generated by Django 5.0.6 on 2025-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("color", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
