# Generated by Django 5.0.6 on 2025-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
